update document
koishijs/v3 pull request #1
Opened 2021-12-04 16:39 UTC by idlist

主要是补充了一些关于数据库的详情。

顺手捉了几个虫，然后增加了一些小贴士（又称喂饭）。

2021-12-04 17:37 UTC, Shigma requested changes

2021-12-04 17:37 UTC, Shigma commented on api/context.md
> +ctx.bots[`${platform}:${botId}`]
selfId 更好

2021-12-04 17:37 UTC, Shigma commented on guide/execute.md
> +Koishi 会自动将被引号（半角或者全角）围住的参数视为一个整体。这在很多场景中都非常有用，下面举出了一些典型的例子：
我其实不知道为啥要改这个

2021-12-04 17:37 UTC, Shigma commented on guide/execute.md
> +- 当希望传入一个空字符串作为参数时（默认的行为是解析为 `true`）
建议 pick 到 v4 文档

2021-12-04 17:37 UTC, Shigma commented on guide/help.md
> +# 帮助系统
没这么叫主要是不觉得这是一个系统

2021-12-04 17:47 UTC, idlist commented on guide/help.md
> +# 帮助系统
那就改回去，不过刚好这文档里其实还漏了个东西（自称隐藏选项但是并没有写 `hidden: true`），下一个 commit 一起改了

2021-12-04 17:48 UTC, idlist commented on guide/execute.md
> +Koishi 会自动将被引号（半角或者全角）围住的参数视为一个整体。这在很多场景中都非常有用，下面举出了一些典型的例子：
我觉得原文引号的对象不明晰，实际应用中只会用引号围住参数，难不成还围住指令不成 🤔

2021-12-04 17:49 UTC, idlist commented on api/context.md
> +ctx.bots[`${platform}:${botId}`]
可以，下个 commit 改

2021-12-04 17:51 UTC, idlist commented on guide/execute.md
> +- 当希望传入一个空字符串作为参数时（默认的行为是解析为 `true`）
这个你自己记得的时候顺手修一下吧，改 1 个字的 typo fix PR 太草了（

2021-12-04 17:57 UTC, Shigma commented on guide/execute.md
> +Koishi 会自动将被引号（半角或者全角）围住的参数视为一个整体。这在很多场景中都非常有用，下面举出了一些典型的例子：
这里表述存在一个因果互换，我们根据是引号围住才判断是参数，而不是因为引号围住了参数所以是整体

2021-12-05 03:25 UTC, idlist commented on guide/execute.md
> +Koishi 会自动将被引号（半角或者全角）围住的参数视为一个整体。这在很多场景中都非常有用，下面举出了一些典型的例子：
那标题要不要也改回来

2021-12-05 03:33 UTC, idlist commented on guide/execute.md
> +Koishi 会自动将被引号（半角或者全角）围住的参数视为一个整体。这在很多场景中都非常有用，下面举出了一些典型的例子：
算了，我不想改这个标题，我还是想让左边的目录中一眼就能看明白引号是做什么的

2021-12-05 03:59 UTC, Shigma approved these changes

2021-12-05 03:59 UTC, merged